[parse]
parse_deps = false

[export]
include = ["CppLoessResult"]
prefix = "fastloess_"
renaming_overrides_prefixing = true

[fn]
rename_args = "None"

[struct]
rename_fields = "None"

[enum]
rename_variants = "ScreamingSnakeCase"
